### ISSUE TITLE
ggttest fails when t.test data argument is used

### ISSUE THREAD

**Issue by Ax3man** [okgreece/gginference#1]
Reproducible example:
```
library(gginference)
test <- t.test(hp ~ am, data = mtcars)
ggttest(test)
```

Also see [SO](https://stackoverflow.com/questions/61034288/why-when-i-run-the-ggttest-there-is-an-error#61034288).

**Comment by kleanthisk10** [comment]
`t.test` doesn't store your data in the output so there is no way that you could extract the data from the list of the output of `t.test`.

The only way to use formula is:

```
library(gginference)
t_test <- t.test(questionnaire$pulse ~ questionnaire$gender)
ggttest(t_test)
```
Original answer here: [How to extract the dataset from an "htest" object when using formula in r](https://stackoverflow.com/questions/61434785/how-to-extract-the-dataset-from-an-htest-object-when-using-formula-in-r)
